---
all:
  children:
    ospf_routers:
      children:
        ios:
          children:
            iosxe:
              hosts:
                csr1:
                  my_areas: [0, 3, 4369]
                  my_nbr_count: 4
                csr2:
                  my_areas: [2]
                  my_nbr_count: 1
                  should_be_stub_rtr: true
            iosclassic:
        iosxr:
          hosts:
            xrv1:
              my_areas: [0, 1, 2]
              my_nbr_count: 4
              should_be_stub_rtr: false
            xrv2:
              my_areas: [4369]
              my_nbr_count: 2
              should_be_asbr: true
              should_be_stub_rtr: true
        nxos:
          hosts:
            n3k1:
              my_areas: [0, 4369]
              my_nbr_count: 3
              should_be_asbr: false
              should_be_stub_rtr: true
            n3k2:
              my_areas: [1, 3]
              my_nbr_count: 2
              should_be_asbr: true
...
