---
- hosts: localhost
  tasks:
    - set_fact:
        text: |-
          Routing Process "ospf 1" with ID 10.0.0.5
          Start time: 00:00:17.043, Time elapsed: 00:00:30.262
          Supports only single TOS(TOS0) routes
          Supports opaque LSA
          Supports Link-local Signaling (LLS)
          Supports area transit capability
          Supports NSSA (compatible with RFC 3101)
          Supports Database Exchange Summary List Optimization (RFC 5243)
          Event-log enabled, Maximum number of events: 1000, Mode: cyclic
          It is an area border and autonomous system boundary router
          Redistributing External Routes from,
          Router is not originating router-LSAs with maximum metric
          Initial SPF schedule delay 5000 msecs
          Minimum hold time between two consecutive SPFs 10000 msecs
          Maximum wait time between two consecutive SPFs 10000 msecs
          Incremental-SPF disabled
          Minimum LSA interval 5 secs
          Minimum LSA arrival 1000 msecs
          LSA group pacing timer 240 secs
          Interface flood pacing timer 33 msecs
          Retransmission pacing timer 66 msecs
          EXCHANGE/LOADING adjacency limit: initial 300, process maximum 300
          Number of external LSA 1. Checksum Sum 0x006D01
          Number of opaque AS LSA 0. Checksum Sum 0x000000
          Number of DCbitless external and opaque AS LSA 0
          Number of DoNotAge external and opaque AS LSA 0
          Number of areas in this router is 2. 1 normal 0 stub 1 nssa
          Number of areas transit capable is 0
          External flood list length 1
          IETF NSF helper support enabled
          Cisco NSF helper support enabled
          Reference bandwidth unit is 100 mbps
             Area BACKBONE(0)
                 Number of interfaces in this area is 3 (1 loopback)
                 Area has no authentication
                 SPF algorithm last executed 00:00:01.771 ago
                 SPF algorithm executed 4 times
                 Area ranges are
                 Number of LSA 58. Checksum Sum 0x1BEC4B
                 Number of opaque link LSA 0. Checksum Sum 0x000000
                 Number of DCbitless LSA 0
                 Number of indication LSA 0
                 Number of DoNotAge LSA 17
                 Flood list length 1
             Area 4
                 Number of interfaces in this area is 1
                 It is a NSSA area
                 Perform type-7/type-5 LSA translation
                 Area has no authentication
                 SPF algorithm last executed 00:00:15.193 ago
                 SPF algorithm executed 3 times
                 Area ranges are
                 Number of LSA 67. Checksum Sum 0x21BA85
                 Number of opaque link LSA 0. Checksum Sum 0x000000
                 Number of DCbitless LSA 0
                 Number of indication LSA 0
                 Number of DoNotAge LSA 0
                 Flood list length 0
    - set_fact:
        data: "{{ text | ios_ospf_basic }}"

    - debug:
        var: data

    - set_fact:
        text: |-
          OSPF Router with ID (10.0.0.1) (Process ID 1)

          Area 0 database summary
            LSA Type      Count    Delete   Maxage
            Router        9        0        0
            Network       1        0        0
            Summary Net   54       0        0
            Summary ASBR  4        0        0
            Type-7 Ext    0        0        0
              Prefixes redistributed in Type-7  0
            Opaque Link   0        0        0
            Opaque Area   0        0        0
            Subtotal      68       0        0

          Area 3 database summary
            LSA Type      Count    Delete   Maxage
            Router        4        0        0
            Network       0        0        0
            Summary Net   64       0        0
            Summary ASBR  6        0        0
            Type-7 Ext    0        0        0
              Prefixes redistributed in Type-7  0
            Opaque Link   0        0        0
            Opaque Area   0        0        0
            Subtotal      74       0        0

          Process 1 database summary
            LSA Type      Count    Delete   Maxage
            Router        13       0        0
            Network       1        0        0
            Summary Net   118      0        0
            Summary ASBR  10       0        0
            Type-7 Ext    0        0        0
            Opaque Link   0        0        0
            Opaque Area   0        0        0
            Type-5 Ext    1        0        0
                Prefixes redistributed in Type-5  0
            Opaque AS     0        0        0
            Non-self      99
            Total         143      0        0

    - set_fact:
        data: "{{ text | ios_ospf_dbsum }}"

    - debug:
        var: data


    - set_fact:
        text: |-
          Interface statistics

              Interface Tunnel102

          Last clearing of interface traffic counters never

          OSPF packets received/sent
            Type          Packets              Bytes
            RX Invalid    0                    0
            RX Hello      49                   2348
            RX DB des     2                    84
            RX LS req     0                    0
            RX LS upd     6                    524
            RX LS ack     3                    152
            RX Total      60                   3108

            TX Failed     0                    0
            TX Hello      49                   4504
            TX DB des     4                    336
            TX LS req     0                    0
            TX LS upd     3                    448
            TX LS ack     2                    188
            TX Total      58                   5476

          OSPF header errors
            Length 1, Instance ID 2, Checksum 3, Auth Type 4,
            Version 5, Bad Source 6, No Virtual Link 7,
            Area Mismatch 8, No Sham Link 9, Self Originated 10,
            Duplicate ID 11, Hello 12, MTU Mismatch 13,
            Nbr Ignored 14, LLS 15, Unknown Neighbor 16,
            Authentication 17, TTL Check Fail 18, Adjacency Throttle 19,
            BFD 20, Test discard 21

          OSPF LSA errors
            Type 22, Length 23, Data 24, Checksum 25

    - set_fact:
        data: "{{ text | ios_ospf_traffic }}"

    - debug:
        var: data

    - set_fact:
        text: |-
          OSPF Router with ID (10.0.0.2) (Process ID 1)

          Microloop avoidance is enabled for protected prefixes, delay 5000 msec

          Loop-free Fast Reroute protected prefixes

          Area  Topology name   Priority   Remote LFA Enabled  TI-LFA Enabled
             0           Base       High                  Yes              No
            51           Base        Low                   No              No

    - set_fact:
        data: "{{ text | ios_ospf_frr }}"

    - debug:
        var: data
